module.exports.ERROR_CODES = {
  REQUIRED_FIELDS_MISSING: 'REQUIRED_FIELDS_MISSING',
  DATE_TIME_UNTIL_IS_NOT_DEFINED: 'DATE_TIME_UNTIL_IS_NOT_DEFINED',
  PROMOTION_IS_FINISHED: 'PROMOTION_IS_FINISHED',
  PROMOTION_NOT_FOUND: 'PROMOTION_NOT_FOUND',
  SERVICE_BELONGS_ANOTHER_ORGANIZATION: 'SERVICE_BELONGS_ANOTHER_ORGANIZATION',
  TARGET_BELONGS_ANOTHER_ORGANIZATION: 'TARGET_BELONGS_ANOTHER_ORGANIZATION',
  TARGET_AND_SERVICE_ARE_NOT_RELATED: 'TARGET_AND_SERVICE_ARE_NOT_RELATED',
  OVERLAP_RESERVATION: 'OVERLAP_RESERVATION',
  PROHIBITED_PROPERTY: 'PROHIBITED_PROPERTY',
  REQUIRED_FILTERS_ARE_MISSED: 'REQUIRED_FILTERS_ARE_MISSED',
  TOO_MANY_COUPONS_FOR_SINGLE_USER: 'TOO_MANY_COUPONS_FOR_SINGLE_USER',
  COUPON_LIMIT_EXCEEDED: 'COUPON_LIMIT_EXCEEDED',
  USER_BID_LIMIT_EXCEEDED: 'USER_BID_LIMIT_EXCEEDED',
  UNABLE_TO_REQUEST_COUPON_FOR_DRAFT_PROMOTION:
    'UNABLE_TO_REQUEST_COUPON_FOR_DRAFT_PROMOTION',
  UNABLE_TO_REQUEST_COUPON_FOR_AUCTION_PROMOTION:
    'UNABLE_TO_REQUEST_COUPON_FOR_AUCTION_PROMOTION',
  CHAT_IS_NOT_AVAILABLE_FOR_USER: 'CHAT_IS_NOT_AVAILABLE_FOR_USER',
}
